config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: %i[create destroy]
  devise_for :users
  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'friends', to: 'users#friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: %i[create destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true
  def self.new_lookup(ticker_symbol)
    client = client_connect
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name,
          last_price: client.price(ticker_symbol))
    rescue StandardError
      nil
    end
  end

  def self.client_connect
    IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.publishable_token,
      secret_token: Rails.application.credentials.secret_token,
      endpoint: 'https://cloud.iexapis.com/v1'
    )
  end

  def self.check_db(ticker)
    where(ticker: ticker).first
  end

  def self.top_10
    client = client_connect
    client.stock_market_list(:mostactive)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def under_stock_limit?
    stocks.count < 10
  end

  def stock_already_tracked?(ticker)
    stock = Stock.check_db(ticker)
    return false unless stock

    stocks.where(id: stock.id).exists?
  end

  def can_track_stock?(ticker)
    under_stock_limit? && !stock_already_tracked?(ticker)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back

    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == id }
  end

  def not_friends?(id_of_friend)
    !friends.where(id: id_of_friend).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "Seguindo #{friend.full_name}"
    else
      flash[:alert] = 'Oops, Algo errado!'
    end
    redirect_to friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Deixou de seguir #{User.find(params[:id]).full_name}"
    redirect_to friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        flash.now[:alert] = "Não foi encontrado nenhuma ação com o codigo: #{params[:stock].upcase}"
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      end
    else
      flash.now[:alert] = 'Por favor entre com um codigo para pesquisar'
      respond_to do |format|
        format.js { render partial: 'users/result' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "#{stock.name} foi adicionado ao seu Portifolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.name} foi removido do seu portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
    @user = current_user
  end

  def friends
    @friends = current_user.friends
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        flash.now[:alert] = "Não foi encontrado nenhum usuario com este nome ou email: #{params[:friend]}"
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      flash.now[:alert] = 'Por favor entre com nome ou email para pesquisar'
      respond_to do |format|
        format.js { render partial: 'users/friend_result' }
      end
    end
  end

  def destroy; end

  def create; end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @top10 = Stock.top_10
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<div class="container px-0" >
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show text-start mt-2" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2 bi" viewBox="0 0 16 16" role="img" aria-label="Success:">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </svg>
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "FinanceTracker", root_path, class: "navbar-brand text-primary fs-4 px-0 py-0 fw-bold" %>
    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Meu Portifolio", my_portfolio_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Amigos", friends_path, class: "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Perfil
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to current_user, class: "dropdown-item" do %>
                  <%= fa_icon 'eye' %>  Ver 
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                  <%= fa_icon 'edit', class: 'text-danger' %>  Editar
                <% end %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                  <%= fa_icon 'sign-out', class: "text-primary" %>
                  Logout
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
        <div class="nav-link text-dark" >
          <%= fa_icon 'user-circle'%>
          <%= current_user.full_name %>
        </div>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
 <% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show text-start" role="alert">
    <h4 class="alert-heading">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2 bi" viewBox="0 0 16 16" role="img" aria-label="Warning:">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </svg>
      the following errors occurred:
    </h4>
    <ul>
      <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/users/_friend_result.html.erb
<div class="row">
  <div class="col-9">
    <%= render 'layouts/messages' %>
  </div>
</div>
<% if @friends %>
  <div class="row">
    <div class="col-9">
      <% @friends.each do |friend| %>
        <div class="card mt-4">
          <div class="card-header d-flex justify-content-between">
            <div class="">
              <strong>Nome:</strong> <%= friend.full_name %>
            </div>
            <div class="">
              <strong>Email:</strong> <%= friend.email %>
            </div>
            <div>
              <%= link_to  user_path(friend), class: "btn btn-sm btn-outline-primary" do %>
                <%= fa_icon 'eye' %>
                Ver Perfil
              <% end %>
              <% if current_user.not_friends?(friend.id) %>
                <%= link_to friendships_path(friend: friend), method: :post, class: "btn btn-sm btn-outline-success" do %>
                  <%= fa_icon 'user-plus' %>
                  Seguir
                <% end %>
              <% else %>
                <button class="btn btn-sm btn-outline-secondary" disabled>
                  <%= fa_icon 'user-plus' %>
                  Seguir
                </button>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector("#results").innerHTML = "<%= j render 'users/friend_result.html' %>";

app/views/users/_friends_table.haml
%table.table.table-hover.table-bordered.mt-3.text-center
 %thead
  %tr
   %th{scope: "col"} Nome
   %th{scope: "col"} Email
   %th{scope: "col"} Ações
 %tbody
  - @friends.each do |friend|
   %tr
    %td 
     = friend.full_name
    %td
     = friend.email
    %td
     = link_to  user_path(friend), class: "btn btn-sm btn-outline-primary me-2" do
      = fa_icon 'eye'
      Ver Perfil
     = link_to "Parar de Seguir", friendship_path(friend), method: :delete, class: "btn btn-sm btn-warning", data: {confirm: "Tem certeza que deseja remover?"}
            
     

app/views/users/_result.html.erb
<% if !@user_stock %>
  <div class="row">
    <div class="col-9">
      <%= render 'layouts/messages' %>
    </div>
  </div>
<% end %>
<% if @stock %>
  <div class="row">
    <div class="col-9">
      <div class="card mt-4">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h5 class="pt-2">
            Codigo: <%= @stock.ticker.upcase %>
          </h5>
          <% if current_user.can_track_stock?(@stock.ticker) %>
            <%= link_to user_stocks_path(user: current_user, ticker: @stock.ticker), remote: true, class: "btn btn-dark btn-sm", method: :post do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
              </svg>
              Adicionar
            <% end %>
          <% else %>
            <span class="badge bg-secondary">
              Você já segue
              <% if !current_user.under_stock_limit? %>
                10 ações
              <% end %>
              <% if current_user.stock_already_tracked?(@stock.ticker) %>
                esta ação
              <% end %>
            </span>
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            Nome da Empresa: <%= @stock.name %>
          </h5>
          <p class="card-text">
            Valor da Ação: US$<%= @stock.last_price.round(2) %>
          </p>
          <img src=<%= "https://storage.googleapis.com/iex/api/logos/#{@stock.ticker.upcase}.png" %> alt=<%= "#{@stock.ticker}.png"  %> >
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector("#results").innerHTML = "<%= j render 'users/result.html' %>";

app/views/users/_table.html.erb
<div class="row mt-3">
  <div class="col-9">
    <table class="table table-hover table-bordered mt-0 text-center">
      <thead>
        <tr>
          <th scope="col">Codigo</th>
          <th scope="col">Nome</th>
          <th scope="col">Preço US$</th>
          <th scope="col">Opções</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <td> <%= stock.ticker.upcase %> </td>
            <td> <%= stock.name %> </td>
            <td> <%= stock.last_price.round(2) %> </td>
            <td>
              <% if current_user.can_track_stock?(stock.ticker) %>
                <%= link_to user_stocks_path(user: current_user, ticker: stock.ticker), remote: true, class: "btn btn-sm btn-dark", method: :post do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                  </svg>
                  Adicionar
                <% end %>
              <% elsif current_user != @user %>
                <span class="badge bg-secondary">
                  Você já segue
                  <% if !current_user.under_stock_limit? %>
                    10 ações
                  <% end %>
                  <% if current_user.stock_already_tracked?(stock.ticker) %>
                    esta ação
                  <% end %>
                </span>
              <% end %>
              <% if current_user == @user %>
                <%= link_to "Remover", user_stock_path(stock), method: :delete, data: {confirm: "Tem certeza?"}, class: "btn btn-sm btn-outline-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/friends.haml
%h1.mt-3 Amigos
%hr
.search-area
 %h3.mb-3 Procurar Amigos
= form_tag search_friend_path, remote: true, method: :get do
 .form-group.row
  .col-sm-9.me-0.pe-0
   = text_field_tag :friend, params[:stock], placeholder: "Nome ou Email", autofocus: true, class: "form-control form-control-lg"
  .col-sm-3.ms-0.ps-0
   = button_tag class: "btn btn-success text-white" do 
    = fa_icon 'search 2x'

#results.mb-0.mt-0
.row.mt-3 
 .col-9 
  - unless @friends.empty?
   = render 'users/friends_table'

app/views/users/my_portfolio.haml
%h1.mt-3 Meu Portfolio
%hr
.search-area
 %h3.mb-3 Procurar Ações
= form_tag search_stock_path, remote: true, method: :get do
 .form-group.row
  .col-sm-9.me-0.pe-0
   = text_field_tag :stock, params[:stock], placeholder: "Codigo da ação", autofocus: true, class: "form-control form-control-lg"
  .col-sm-3.ms-0.ps-0
   = button_tag class: "btn btn-success text-white" do 
    = fa_icon 'search 2x'

#results.mb-0.mt-0

- if !@tracked_stocks.empty?
 = render 'users/table'
- else
 %h5.fw-normal.mt-3 Você não está rastreando nenhuma ação

app/views/users/show.haml
%h1.mt-3 Detalhes do Usuário

%hr
- if current_user.not_friends?(@user.id) && current_user != @user
 = link_to friendships_path(friend: @user), method: :post, class: "btn btn-sm btn-outline-success" do
  = fa_icon 'user-plus'
  Seguir
- else
 %button{class: "btn btn-sm btn-outline-secondary", disabled: true}
  = fa_icon 'user-plus'
  Seguir
%h4.fw-normal.mt-3
 = "Nome: #{@user.full_name}"

%h4.fw-normal.mt-3
 = "Email: #{@user.email}"
%h2.mt-3 Ações Rastreadas
%hr
- if !@tracked_stocks.empty?
 = render 'users/table'
- else
 %h5.fw-normal Este Usuário não está rastreando nenhuma ação

app/views/welcome/index.html.erb
<h1 class="text-center mt-2 text-secondary">Top 10 Ações</h1>
<hr />
<div class="d-flex flex-wrap justify-content-center">
  <% @top10.each do |stock| %>
    <div class="card mt-4 card-top10 mx-2">
      <div class="card-header bg-light">
        <h5 class="pt-2 fw-normal">
          Codigo: <%= stock.symbol.upcase %>
        </h5>
      </div>
      <div class="card-body">
        <h5 class="card-title fw-normal">
          Nome: <%= stock.company_name %>
        </h5>
        <p class="card-text">
          Valor da Ação: US$<%= stock.latest_price.to_f.round(2) %>
        </p>
      </div>
    </div>
  <% end %>
</div>